# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0bcd5edcb03fe03e220a85cefb22f852"
name = "qrcode-doc-demo"
application_url = "https://tuner-charger-idle-relevant.trycloudflare.com"
embedded = true
handle = "qrcode-doc-demo"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://tuner-charger-idle-relevant.trycloudflare.com/auth/callback", "https://tuner-charger-idle-relevant.trycloudflare.com/auth/shopify/callback", "https://tuner-charger-idle-relevant.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
